# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-08 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokecards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='static_image_path',
            field=models.CharField(default='images/logo.png', max_length=200),
        ),
    ]
